### ISSUE TITLE
is this project suitable for windows as fdd to usb converter

### ISSUE THREAD

**Issue by youxiaojie** [catphish/amiga-floppy#1]
is this project suitable for windows as fdd to usb converter

**Comment by catphish** [comment]
It really depends how you want to use it. Initially, this project will provide the ability to read Amiga floppy disks to an image file, and write disks from an image file.
In the future it is hoped that the project will also support reading and writing images in other disk formats, and also providing direct access to disks, however there is no ETA for any of this.
What is your specific use case?

**Comment by catphish** [comment]
If your intention is simply to use this as a normal PC USB floppy drive, it would probably be better to buy an existing one. If you want to read and write unusual (non-PC) disks then this project can help :)
